### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"regis",
    "email":"regis@mail.com",
    "password":"password123"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"gis@mail.com",
    "password":"password123"
}

### whoami
GET http://localhost:3000/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InJlZ2lzIiwiZW1haWwiOiJyZWdpc0BtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE0NzIzMDQxfQ.pGu7HgKYLB2Svuv9CWRefeusVsYr4MuOROJwAA69HAo

### create new admin
POST http://localhost:3000/api/v1/create-admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImdpcyIsImVtYWlsIjoiZ2lzQG1haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzE0NzIzMTg2fQ.ZE3kpcT_sPozfBwlQOlV8fxouEuhRM4hbIa35hxjdiQ

{
    "name":"gis",
    "email":"gis@mail.com",
    "password":"password123"
}


### register
POST https://expressjs-development-acb4.up.railway.app/api/v1/register
Content-Type: application/json

{
    "name":"gis",
    "email":"gis@mail.com",
    "password":"password123"
}

### login
POST https://expressjs-development-acb4.up.railway.app/api/v1/login
Content-Type: application/json

{
    "email":"gis@mail.com",
    "password":"password123"
}

### whoami
GET https://expressjs-development-acb4.up.railway.app/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InJlZ2lzIiwiZW1haWwiOiJyZWdpc0BtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE0NzI1MDM2fQ.-dDNmqdfplZkXxBBw-KF6edhlTIYyQ2SImkDpOJvyyA

### create new admin
POST https://expressjs-development-acb4.up.railway.app/api/v1/create-admin
Content-Type: application/json


{
    "name":"gissr",
    "email":"gissr@mail.com",
    "password":"password123"
}

# You can access: https://expressjs-development-acb4.up.railway.app/ 


### register
POST https://expressjsprod-production.up.railway.app/api/v1/register
Content-Type: application/json

{
    "name":"gisamang",
    "email":"gisamang@mail.com",
    "password":"password123"
}

### login
POST https://expressjsprod-production.up.railway.app/api/v1/login
Content-Type: application/json

{
    "email":"gisamang@mail.com",
    "password":"password123"
}

### whoami
GET https://expressjsprod-production.up.railway.app/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Imdpc2FtYW5nIiwiZW1haWwiOiJnaXNhbWFuZ0BtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE0NzQxMDY3fQ.NTRQd9Ki1f5oxrs2msurpu4kwRNdZVVI4wYneebmurY

### create new admin
POST https://expressjsprod-production.up.railway.app/api/v1/create-admin
Content-Type: application/json


{
    "name":"gissr",
    "email":"gissr@mail.com",
    "password":"password123"
}

# You can access: https://expressjsprod-production.up.railway.app/